# Generated by Django 5.1.7 on 2025-04-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('ai', 'Artificial Intelligence'), ('economics', 'Economics'), ('finance', 'Finance'), ('business', 'Business'), ('startup', 'Startups & Entrepreneurship'), ('cybersecurity', 'Cybersecurity'), ('data_science', 'Data Science'), ('blockchain', 'Blockchain'), ('cloud', 'Cloud Computing'), ('machine_learning', 'Machine Learning'), ('software_dev', 'Software Development')], default='tech', max_length=50),
        ),
    ]
